service: default

runtime: python37

handlers:
- url: /
  static_files: (.*)
  upload: (.*)

- url: /scripts/(.*)
  static_files: scripts/\1
  upload: scripts/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)
